# generated by datamodel-codegen:
#   filename:  box.json
#   timestamp: 2023-02-17T16:06:05+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, Field

from . import placement


class IBox(BaseModel):
    class Config:
        extra = Extra.forbid

    Length: float = Field(..., description='The length of the box')
    Width: float = Field(..., description='The width of the box')
    Height: float = Field(..., description='The height of the box')
    Placement: placement.Model
