# generated by datamodel-codegen:
#   filename:  cone.json
#   timestamp: 2023-02-17T16:06:05+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, Field

from . import placement


class ICone(BaseModel):
    class Config:
        extra = Extra.forbid

    Radius1: float = Field(..., description='The bottom radius of the cone')
    Radius2: float = Field(..., description='The top radius of the cone')
    Height: float = Field(..., description='The height of the cone')
    Angle: float = Field(..., description='The angle of the cone')
    Placement: placement.Model
