# generated by datamodel-codegen:
#   filename:  cut.json
#   timestamp: 2023-02-17T16:06:05+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, Field

from . import placement


class ICut(BaseModel):
    class Config:
        extra = Extra.forbid

    Base: str = Field(..., description='The base of the cut operator')
    Tool: str = Field(..., description='The tool of the cut operator')
    Refine: bool = Field(..., description='Refine shape')
    Placement: placement.Model
