# generated by datamodel-codegen:
#   filename:  extrusion.json
#   timestamp: 2023-02-17T16:06:05+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field

from . import placement


class IExtrusion(BaseModel):
    class Config:
        extra = Extra.forbid

    Base: str = Field(..., description='Shape to extrude')
    Dir: List[float] = Field(..., description='Direction of extrusion')
    LengthFwd: float = Field(..., description='Length of extrusion along the direction')
    LengthRev: float = Field(
        ..., description='Length of extrusion against the direction'
    )
    Solid: bool = Field(..., description='If true, creating a solid')
    Placement: placement.Model
