# generated by datamodel-codegen:
#   filename:  intersection.json
#   timestamp: 2023-02-17T16:06:05+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field

from . import placement


class IIntersection(BaseModel):
    class Config:
        extra = Extra.forbid

    Shapes: List[str] = Field(..., description='The objects to intersect')
    Refine: bool = Field(..., description='Refine shape')
    Placement: placement.Model
