from ._schema.box import IBox
from ._schema.cone import ICone
from ._schema.cut import ICut
from ._schema.cylinder import ICylinder
from ._schema.extrusion import IExtrusion
from ._schema.fuse import IFuse
from ._schema.intersection import IIntersection
from ._schema.jcad import Parts
from ._schema.sphere import ISphere
from ._schema.torus import ITorus
