/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Cone
 */
export interface ICone {
  /**
   * The bottom radius of the cone
   */
  Radius1: number;
  /**
   * The top radius of the cone
   */
  Radius2: number;
  /**
   * The height of the cone
   */
  Height: number;
  /**
   * The angle of the cone
   */
  Angle: number;
  /**
   * Placement of the box
   */
  Placement: {
    /**
     * Position of the Placement
     */
    Position: number[];
    /**
     * Axis of the Placement
     */
    Axis: number[];
    /**
     * Angle of the Placement
     */
    Angle: number;
  };
}
