/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Cut
 */
export interface ICut {
  /**
   * The base of the cut operator
   */
  Base: string;
  /**
   * The tool of the cut operator
   */
  Tool: string;
  /**
   * Refine shape
   */
  Refine: boolean;
  /**
   * Placement of the box
   */
  Placement: {
    /**
     * Position of the Placement
     */
    Position: number[];
    /**
     * Axis of the Placement
     */
    Axis: number[];
    /**
     * Angle of the Placement
     */
    Angle: number;
  };
}
