/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "parts".
 */
export type Parts =
  | "Part::Box"
  | "Part::Cylinder"
  | "Part::Sphere"
  | "Part::Cone"
  | "Part::Torus"
  | "Part::Cut"
  | "Part::MultiFuse"
  | "Part::MultiCommon";
/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "jcadModel".
 */
export type IJCadModel = IJCadObject[];

export interface IJCadContent {
  objects: IJCadModel;
  options?: {
    [k: string]: any;
  };
  metadata?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^.*$".
     */
    [k: string]: string;
  };
}
/**
 * This interface was referenced by `IJCadContent`'s JSON-Schema
 * via the `definition` "jcadObject".
 */
export interface IJCadObject {
  name: string;
  visible: boolean;
  shape?: Parts;
  parameters?: {
    [k: string]: any;
  };
  operators?: {
    [k: string]: any;
  }[];
  dependencies?: string[];
}
