/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Torus
 */
export interface ITorus {
  /**
   * The radius of the torus
   */
  Radius1: number;
  /**
   * The radius of the torus
   */
  Radius2: number;
  /**
   * The angle of the torus
   */
  Angle1: number;
  /**
   * The angle of the torus
   */
  Angle2: number;
  /**
   * The angle of the torus
   */
  Angle3: number;
  /**
   * Placement of the box
   */
  Placement: {
    /**
     * Position of the Placement
     */
    Position: number[];
    /**
     * Axis of the Placement
     */
    Axis: number[];
    /**
     * Angle of the Placement
     */
    Angle: number;
  };
}
