name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pydantic
  - ypywidgets
  - yjs-widgets
  - comm
  - pip:
      - ./jupytercad_lab-x.x.x-py3-none-any.whl
