name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pydantic
  - ypywidgets
  - yjs-widgets
  - comm
  - pip:
    - ../python/jupytercad_lab/dist/jupytercad*.whl
