#!/usr/bin/env python3
import sys
import shutil
import os

argv = sys.argv[1:] + ["--debug"]
print(argv)

# Convert from jupyter-notebook based to jupyter-lab based start-up
def nb2jps(s):
    return s.replace("jupyter-notebook", "jupyter-lab").replace("--NotebookApp.", "--ServerApp.")

new_argv = list(map(nb2jps, argv.copy()))
print(new_argv)

with open(".startup_args.txt", "w") as fid:
    fid.write(str(new_argv))

os.execv(shutil.which(new_argv[0]), new_argv)